services:
  db:
    image: postgres:16
    ports:
      - 5432:5432
    # volumes:
    #   - ./postgres/init:docker-entrypoint-initdb.d                    
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DB: "rss"